---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Сайт должен иметь мобильную версию
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
implicit:
 - Для оформления заказа нужна регистрация на сайте
 - Все данные при регистрации отправляются на сервер
 - При добавлении товара неавторизованным пользователем, происходит переход на форму входа
 - Форма входа корректно работает, зарегистрированные пользователи могут войти
 - При нажатии на кнопку заказа товаров в корзине все данные о заказе отправляются на сервер
